language: cpp

compiler:
  - clang

before_install:
  - sudo add-apt-repository ppa:kalakris/cmake -y
  - sudo apt-get update -qq
  - sudo apt-get install cmake
  - sudo apt-get install -qq libcurl4-openssl-dev

before_script:
  - cd build
  - cmake ..

script:
  - make all
  - make test