language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo add-apt-repository ppa:smspillaz/cmake-2.8.12 -y
  - sudo apt-get update -qq
  - sudo apt-get install cmake
  - sudo apt-get install -qq libcurl4-openssl-dev
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.9; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi

before_script:
  - cd build
  - cmake ..

script:
  - make all
  - make test